#Source: https://stackoverflow.com/questions/54114678/how-to-fix-argument-must-be-a-string-typeerror
# Generated by Django 2.1.4 on 2019-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterdata',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
    ]