#Source: https://stackoverflow.com/questions/65339753/typeerror-coercing-to-unicode-need-string-or-buffer-datetime-timedelta-found
from datetime import timedelta
import datetime

#notice the additional brackets to keep the 2 slots as two separate lists. So, 930-1230 is one slot, 1330-1400 is an another.

# HOURS AND APPOINTMENTS ARE GENERATED BY GATHERING DATA FROM DATABASE
hours = [[u'08:00', u'17:00']]
appointments = [(u'12:00', u'12:30'), (u'10:30', u'11:00')]

def get_slots(hours, appointments, duration=timedelta(hours=1)):
    slots = sorted([(hours[0][0], hours[0][0])] + appointments + [(hours[0][1], hours[0][1])])
    for start, end in ((slots[i][1], slots[i+1][0]) for i in range(len(slots)-1)):
        assert start <= end, "Cannot attend all appointments"
        while start + duration <= end:
            json = []
            json.append("{:%H:%M} - {:%H:%M}".format(start, start + duration))
            start += duration
        return json

if __name__ == "__main__":
    get_slots(hours, appointments)