# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/54114678/how-to-fix-argument-must-be-a-string-typeerror
# Generated by Django 2.1.4 on 2019-01-09 16:29

from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
try:
    from django.db import migrations, models
    _l_(647889)

except ImportError:
    pass


class Migration(_a_(647891, _n_(647890, "migrations", lambda: migrations), "Migration")):
    _l_(647900)


    dependencies = [
        ('system', '0001_initial'),
    ]
    _l_(647892)

    operations = [
        _c_(647898, _a_(647894, _n_(647893, "migrations", lambda: migrations), "AlterField"), model_name='semesterdata',
            name='status',
            field=_c_(647897, _a_(647896, _n_(647895, "models", lambda: models), "CharField"), choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
    ]
    _l_(647899)