# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/73845215/mw-instance-middlewareadapted-handler-typeerror-module-object-is-not-call
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
"""
Django settings for passmanager project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
try:
    from pathlib import Path
    _l_(582249)

except ImportError:
    pass
try:
    import os
    _l_(582251)

except ImportError:
    pass
try:
    from django.utils.timezone import activate
    _l_(582253)

except ImportError:
    pass
try:
    from django.conf import settings
    _l_(582255)

except ImportError:
    pass
try:
    from pytz import timezone
    _l_(582257)

except ImportError:
    pass

_c_(582261, _n_(582258, "activate", lambda: activate), _a_(582260, _n_(582259, "settings", lambda: settings), "TIME_ZONE"))
_l_(582262)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = _a_(582269, _a_(582268, _c_(582267, _a_(582266, _c_(582265, _n_(582263, "Path", lambda: Path), _n_(582264, "__file__", lambda: __file__)), "resolve")), "parent"), "parent")
_l_(582270)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Removed!'
_l_(582271)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
_l_(582272)

ALLOWED_HOSTS = ['*']
_l_(582273)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'crispy_forms'
    
]
_l_(582274)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
_l_(582275)

ROOT_URLCONF = 'passmanager.urls'
_l_(582276)

# AUTHENTICATION_BACKENDS = ( 'urlcrypt.auth_backends.UrlCryptBackend' )

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            _n_(582277, "BASE_DIR", lambda: BASE_DIR) / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
_l_(582278)

WSGI_APPLICATION = 'passmanager.wsgi.application'
_l_(582279)

CRISPY_TEMPLATE_PACK = 'uni_form'
_l_(582280)
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'PasswordManager',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host': 'mongodb+srv://loopassembly:<removed!>@cluster0.cwtfb.mongodb.net/test'
            }  
        }
}
_l_(582281)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
_l_(582282)


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
_l_(582283)

TIME_ZONE = 'UTC'
_l_(582284)

USE_I18N = True
_l_(582285)

USE_TZ = True
_l_(582286)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
_l_(582287)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

STATIC_URL = 'static/'
_l_(582288)
STATIC_ROOT = _n_(582289, "BASE_DIR", lambda: BASE_DIR) / 'staticfiles'
_l_(582290)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
_l_(582291)
MEDIA_ROOT = _c_(582296, _a_(582294, _a_(582293, _n_(582292, "os", lambda: os), "path"), "join"), _n_(582295, "BASE_DIR", lambda: BASE_DIR), 'media')
_l_(582297)
MEDIA_URL = '/media/'
_l_(582298)