#Source: https://stackoverflow.com/questions/64391262/why-am-i-getting-the-error-attributeerror-mysqlcursor-object-has-no-attribu
@app.route('/generate/file-manip',methods = ["GET","POST"]) # for saving the password(s)
def save_file():
  pass_output_lst = [] #for passwords
  desc_output_lst = [] #for descriptions of the password
  encrypted_pass_output_lst = [] #storing passwords after encryption
  encrypted_desc_output_lst = [] #storing descriptions of passwords after encryption
  UPLOAD_FOLDER = os.getcwd()
  app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
  if request.method == "POST": # checking if the request method is POST
      pass_file = request.files['passfile'] #requesting the name of the password saving file
      pass_file_Name = secure_filename(pass_file.filename) #storing the name of the password saving file
      desc_file = request.files['descfile'] #for the file storing descriptions of the file
      desc_file_Name =secure_filename(desc_file.filename)
      key = Fernet.generate_key() # generating a key
      key_init = Fernet(key)  # storing the key for encrypting purpose
      key_file = request.files['keyfile']  # requesting the key saving file
      key_file_name = secure_filename(key_file.filename) #storing the name of the key saving file
      file_lst = [pass_file_Name,desc_file_Name,key_file_name]

      for i in GlobalData.password:
       encrypted_pass_output_lst.append(key_init.encrypt(bytes(i.passwd,encoding="utf-8")))
       encrypted_desc_output_lst.append(key_init.encrypt(bytes(i.desc,encoding="utf-8")))
      with open(pass_file_Name,"wb+") as k:

       for i in encrypted_pass_output_lst:
         k.write(i)
         k.write(b'\n')

      with open(desc_file_Name,"wb+") as k:

       for i in encrypted_desc_output_lst:
         k.write(i)
         k.write(b'\n')
      with open(key_file_name,"wb+") as k:
        k.write(key)


  if GlobalData.password == []: # for showing the error when no password is created
    return render_template('semantic-error.html',message = "Illegal method. Can't save the file when no password is generated")
  else: #[pass_file_Name,desc_file_Name,key_file_name]

        zip_obj = zipfile.ZipFile('/home/ZCDS4327/proj/cs_proj_pro_1/zipfile.zip','w')#creating a zip file and storing it inside an object

        #SQL Execution(an SQL table stores number of password generated by the user along with it's date and time)
        getDate = datetime.datetime.now() #date and time of generating the passwords
        cursor = mydb.cursor()
        n_passwd = len(GlobalData.password) #number of passwords generated
        insert_query = "INSERT INTO password_table(n_passwd,c_date) VALUES(%s,%s)" %(n_passwd,getDate) #inserting the passwords inside the table password_site
        cursor.exceute(insert_query)
        mydb.commit()


        for i in file_lst:
            zip_obj.write(i,compress_type =zipfile.ZIP_DEFLATED) #inserting the required files inside the zip file
        zip_obj.close()
        zip_obj_name = zip_obj.filename
        for i in file_lst:
            os.remove(i) #removing the txt files
        del file_lst
        return send_file(zip_obj_name),os.remove('/home/ZCDS4327/proj/cs_proj_pro_1/zipfile.zip') #downloading the zipfile and deleting it from the working directory