# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/64391262/why-am-i-getting-the-error-attributeerror-mysqlcursor-object-has-no-attribu
#SQL Execution(an SQL table stores number of password generated by the user along with it's date and time)
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
getDate = _c_(593401, _a_(593400, _a_(593399, _n_(593398, "datetime", lambda: datetime), "datetime"), "now")) #date and time of generating the passwords
_l_(593402) #date and time of generating the passwords
cursor = _c_(593405, _a_(593404, _n_(593403, "mydb", lambda: mydb), "cursor"))
_l_(593406)
n_passwd = _c_(593410, _n_(593407, "len", lambda: len), _a_(593409, _n_(593408, "GlobalData", lambda: GlobalData), "password")) #number of passwords generated
_l_(593411) #number of passwords generated
insert_query = "INSERT INTO password_table(n_passwd,c_date) VALUES(%s,%s)" %(_n_(593412, "n_passwd", lambda: n_passwd),_n_(593413, "getDate", lambda: getDate)) #inserting the passwords inside the table password_site
_l_(593414) #inserting the passwords inside the table password_site
_c_(593418, _a_(593416, _n_(593415, "cursor", lambda: cursor), "exceute"), _n_(593417, "insert_query", lambda: insert_query))
_l_(593419)
_c_(593422, _a_(593421, _n_(593420, "mydb", lambda: mydb), "commit"))
_l_(593423)