# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/73190803/migrations-error-in-django-attributeerror-str-object-has-no-attribute-meta
# Generated by Django 4.0.6 on 2022-08-01 07:57

from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
try:
    from django.conf import settings
    _l_(635407)

except ImportError:
    pass
try:
    from django.db import migrations, models
    _l_(635409)

except ImportError:
    pass
try:
    import django.db.models.deletion
    _l_(635411)

except ImportError:
    pass


class Migration(_a_(635413, _n_(635412, "migrations", lambda: migrations), "Migration")):
    _l_(635446)


    initial = True
    _l_(635414)

    dependencies = [
        _c_(635419, _a_(635416, _n_(635415, "migrations", lambda: migrations), "swappable_dependency"), _a_(635418, _n_(635417, "settings", lambda: settings), "AUTH_USER_MODEL")),
        ('book', '0001_initial'),
    ]
    _l_(635420)

    operations = [
        _c_(635444, _a_(635422, _n_(635421, "migrations", lambda: migrations), "CreateModel"), name='Reader',
            fields=[
                ('rid', _c_(635425, _a_(635424, _n_(635423, "models", lambda: models), "AutoField"), primary_key=True, serialize=False)),
                ('photo_url', _c_(635428, _a_(635427, _n_(635426, "models", lambda: models), "CharField"), blank=True, max_length=200, null=True)),
                ('bio', _c_(635431, _a_(635430, _n_(635429, "models", lambda: models), "CharField"), blank=True, max_length=200, null=True)),
                ('read_books', _c_(635434, _a_(635433, _n_(635432, "models", lambda: models), "ManyToManyField"), through='reads.Reads', to='book.book')),
                ('user', _c_(635443, _a_(635436, _n_(635435, "models", lambda: models), "OneToOneField"), on_delete=_a_(635440, _a_(635439, _a_(635438, _a_(635437, django, "db"), "models"), "deletion"), "CASCADE"), to=_a_(635442, _n_(635441, "settings", lambda: settings), "AUTH_USER_MODEL"))),
        ],
        options={
            'db_table': 'reader',
        },
    ),
]
    _l_(635445)