# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/57858987/how-to-fix-attributeerror-settings-object-has-no-attribute-root-urlconf
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
"""
Django settings for producthunt project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@(b=ndac@9k%w#y7(h5p!^a!)6y_p2&oln@lsz6x61=wyusg4('
_l_(429407)
try:
    import os
    _l_(429409)

except ImportError:
    pass
try:
    import django
    _l_(429411)

except ImportError:
    pass
_c_(429414, _a_(429413, _n_(429412, "django", lambda: django), "setup"))
_l_(429415)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = _c_(429428, _a_(429418, _a_(429417, _n_(429416, "os", lambda: os), "path"), "dirname"), _c_(429427, _a_(429421, _a_(429420, _n_(429419, "os", lambda: os), "path"), "dirname"), _c_(429426, _a_(429424, _a_(429423, _n_(429422, "os", lambda: os), "path"), "abspath"), _n_(429425, "__file__", lambda: __file__))))
_l_(429429)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
_l_(429430)

ROOT_URLCONF = 'producthunt.urls'
_l_(429431)

ALLOWED_HOSTS = []
_l_(429432)

# Application definition

INSTALLED_APPS = [
    'compressor',
    'django.contrib.sites',
    'django_comments',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'producthunt',
    'links',
    'registration',
]
_l_(429433)
try:
    from django.urls import reverse
    _l_(429435)

except ImportError:
    pass

LOGIN_URL=_c_(429437, _n_(429436, "reverse", lambda: reverse), 'login')
_l_(429438)
LOGIN_REDIRECT_URL = _c_(429440, _n_(429439, "reverse", lambda: reverse), 'home')
_l_(429441)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
_l_(429442)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
_l_(429443)

WSGI_APPLICATION = 'producthunt.wsgi.application'
_l_(429444)

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _c_(429449, _a_(429447, _a_(429446, _n_(429445, "os", lambda: os), "path"), "join"), _n_(429448, "BASE_DIR", lambda: BASE_DIR), 'db.sqlite3'),
    }
}
_l_(429450)

SITE_ID = 1
_l_(429451)

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
_l_(429452)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'
_l_(429453)

TIME_ZONE = 'UTC'
_l_(429454)

USE_I18N = True
_l_(429455)

USE_L10N = True
_l_(429456)

USE_TZ = True
_l_(429457)

COMPRESS_ENABLED = True
_l_(429458)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
_l_(429459)
STATIC_ROOT = 'static'
_l_(429460)
MEDIA_ROOT = 'media'
_l_(429461)
MEDIA_URL = '/media/'
_l_(429462)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
_l_(429463)

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)
_l_(429464)